# Generated by Django 4.2.16 on 2024-10-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
        ('klasses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='newspapers',
            field=models.ManyToManyField(blank=True, to='newspaper.classnewspaper'),
        ),
    ]
