# Generated by Django 4.2.16 on 2024-10-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klasses', '0002_alter_klass_newspapers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klass',
            name='newspapers',
        ),
    ]
