# Generated by Django 4.2.16 on 2024-10-25 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klasses', '0003_remove_klass_newspapers'),
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classnewspaper',
            name='class_name',
        ),
        migrations.AddField(
            model_name='classnewspaper',
            name='klass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='newspapers', to='klasses.klass'),
            preserve_default=False,
        ),
    ]
