# Generated by Django 4.2.16 on 2024-10-26 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klasses', '0003_remove_klass_newspapers'),
        ('newspaper', '0002_remove_classnewspaper_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classnewspaper',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='classnewspaper',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='classnewspaper',
            name='image',
            field=models.ImageField(upload_to='newspapers/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='classnewspaper',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newspapers', to='klasses.klass', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='classnewspaper',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
